apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: test-nginx-volume
          mountPath: /test

    - name: ubuntu
      image: ubuntu
      tty: true
      volumeMounts:
        - name: test-nginx-volume
          mountPath: /test2

  volumes:
    - name: test-nginx-volume
      emptyDir: {}
